//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsisModel.EntityDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public AcademicYear()
        {
            this.StudentCurrentYears = new HashSet<StudentCurrentYear>();
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public int AcademicYearID { get; set; }
        public int SchoolRefID { get; set; }
        public string DisplayYear { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ActiveYear { get; set; }
    
        public virtual ICollection<StudentCurrentYear> StudentCurrentYears { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
