//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsisModel.EntityDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public int CurrentYearRefID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Latefee { get; set; }
        public string InvoiceDate { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual StudentCurrentYear StudentCurrentYear { get; set; }
    }
}
