//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsisModel.EntityDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolClass
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int SchoolRefID { get; set; }
    
        public virtual School School { get; set; }
    }
}
