//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsisModel.EntityDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.AcademicYears = new HashSet<AcademicYear>();
            this.SchoolClasses = new HashSet<SchoolClass>();
            this.StudentCurrentYears = new HashSet<StudentCurrentYear>();
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public int LastRegNo { get; set; }
        public Nullable<int> Selected { get; set; }
        public string Address_Address1 { get; set; }
        public string Address_Address2 { get; set; }
        public string Address_City { get; set; }
        public string Address_Pincode { get; set; }
        public string Address_Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
    
        public virtual ICollection<AcademicYear> AcademicYears { get; set; }
        public virtual ICollection<SchoolClass> SchoolClasses { get; set; }
        public virtual ICollection<StudentCurrentYear> StudentCurrentYears { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
