//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsisModel.EntityDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentCurrentYears = new HashSet<StudentCurrentYear>();
        }
    
        public System.Guid StudentID { get; set; }
        public string Address_Address1 { get; set; }
        public string Address_Address2 { get; set; }
        public string Address_City { get; set; }
        public string Address_Pincode { get; set; }
        public string Address_Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public byte Sex { get; set; }
        public System.DateTime DOB { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string MothersPhone { get; set; }
        public string FathersPhone { get; set; }
        public string FathersQualification { get; set; }
        public string MothersQualifiication { get; set; }
        public string MotherTongue { get; set; }
        public string IdentificationMarks { get; set; }
        public string KnowMedicalCondition { get; set; }
        public string SpecialTalents { get; set; }
        public string ReasonForOlivekids { get; set; }
        public string PlayschoolExperience { get; set; }
        public string DateOfJoining { get; set; }
        public string CenterCode { get; set; }
        public int RegistrationNo { get; set; }
        public decimal AdmissionFee { get; set; }
        public string TotalCourseFee { get; set; }
        public Nullable<decimal> TermFee { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual ICollection<StudentCurrentYear> StudentCurrentYears { get; set; }
    }
}
